FROM forrestzhang/bioconda-base

MAINTAINER Tao Zhang "forrestzhang1982@gmail.com"

RUN conda install samtools bwa bowtie bowtie2 picard cutadapt fastqc sra-tools -y

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.utf8
ENV LC_ALL en_US.UTF-8